// main() for the test binary is generated by tests/test_main.cpp. This file
// is an ordinary doctest file — copy it as the starting point for new tests.
#include "doctest.h"

#include "prime.h"

// normal case: a typical prime number is identified correctly
TEST_CASE("isPrime returns true for a prime number") {
    CHECK(isPrime(7) == true);
}

// wrong case: a typical non-prime (composite) number is rejected
TEST_CASE("isPrime returns false for a composite number") {
    CHECK(isPrime(9) == false);
}

// edge case: boundary values (negative, zero, one, smallest prime)
TEST_CASE("isPrime handles boundary values") {
    CHECK(isPrime(-1) == false);
    CHECK(isPrime(0) == false);
    CHECK(isPrime(1) == false);
    CHECK(isPrime(2) == true);
}
